import { query } from './db.js';
import { requestWorkspaceTransfer,listTransferRequests,cancelTransferRequest } from './workspace-transfers.js';
const owner = (await query(`SELECT id FROM users WHERE username='lucas'`)).rows[0];
const workspace = (await query(`SELECT id FROM workspaces WHERE owner_id=$1 AND is_main=false LIMIT 1`,[owner.id])).rows[0];
if (!workspace) throw new Error('No owned workspace available for request test');
const request = await requestWorkspaceTransfer(workspace.id,'test',owner.id,'user');
const listed = await listTransferRequests(owner.id,'user');
if (!listed.some(item=>item.id===request.id)) throw new Error('Owner request not visible');
await cancelTransferRequest(request.id,owner.id,'user');
console.log(JSON.stringify({ requested:true,visible:true,cancelled:true }));
process.exit(0);
